version: "3.5"
networks:
    mimir-frontend-dev-network:
        name: mimir-frontend-dev-network
services:
    mimir-frontend-dev:
        container_name: mimir-frontend-dev
        image: node:latest
        volumes:
            - ./app:/app
        working_dir: /app
        ports:
            - "8080:8080"
        command: "bash -c 'yarn && yarn run dev-docker'"
        networks:
            - mimir-frontend-dev-network
